### ISSUE TITLE
"Application download did not succeed"

### ISSUE THREAD

**Issue by ghost** [xfurry/eventAI_tool#2]
When trying to run setup.exe or EventAI.Creator.application, I get the following error.

I am running Win8.1.

"Application download did not succeed. Check your network connection, or contact your system administrator or network service provider."

```
PLATFORM VERSION INFO
    Windows             : 6.2.9200.0 (Win32NT)
    Common Language Runtime     : 4.0.30319.42000
    System.Deployment.dll       : 4.6.1055.0 built by: NETFXREL2
    clr.dll             : 4.6.1055.0 built by: NETFXREL2
    dfdll.dll           : 4.6.1055.0 built by: NETFXREL2
    dfshim.dll          : 6.3.9600.16384 (winblue_rtm.130821-1623)

SOURCES
    Deployment url          : file:///C:/Users/Eric/Desktop/eventAI_tool-master/EventAI_creator/EventAI%20Creator.application
    Deployment Provider url     : http://radu-pc/EventAI%20Creator/EventAI%20Creator.application

ERROR SUMMARY
    Below is a summary of the errors, details of these errors are listed later in the log.
    * Activation of C:\Users\Eric\Desktop\eventAI_tool-master\EventAI_creator\EventAI Creator.application resulted in exception. Following failure messages were detected:
        + Downloading http://radu-pc/EventAI Creator/EventAI Creator.application did not succeed.
        + The remote name could not be resolved: 'radu-pc'

COMPONENT STORE TRANSACTION FAILURE SUMMARY
    No transaction error was detected.

WARNINGS
    * The manifest for this application does not have a signature. Signature validation will be ignored.

OPERATION PROGRESS STATUS
    * [5/8/2016 8:38:10 PM] : Activation of C:\Users\Eric\Desktop\eventAI_tool-master\EventAI_creator\EventAI Creator.application has started.

ERROR DETAILS
    Following errors were detected during this operation.
    * [5/8/2016 8:38:12 PM] System.Deployment.Application.DeploymentDownloadException (Unknown subtype)
        - Downloading http://radu-pc/EventAI Creator/EventAI Creator.application did not succeed.
        - Source: System.Deployment
        - Stack trace:
            at System.Deployment.Application.SystemNetDownloader.DownloadSingleFile(DownloadQueueItem next)
            at System.Deployment.Application.SystemNetDownloader.DownloadAllFiles()
            at System.Deployment.Application.FileDownloader.Download(SubscriptionState subState)
            at System.Deployment.Application.DownloadManager.DownloadManifestAsRawFile(Uri& sourceUri, String targetPath, IDownloadNotification notification, DownloadOptions options, ServerInformation& serverInformation)
            at System.Deployment.Application.DownloadManager.DownloadDeploymentManifestDirect(SubscriptionStore subStore, Uri& sourceUri, TempFile& tempFile, IDownloadNotification notification, DownloadOptions options, ServerInformation& serverInformation)
            at System.Deployment.Application.DownloadManager.FollowDeploymentProviderUri(SubscriptionStore subStore, AssemblyManifest& deployment, Uri& sourceUri, TempFile& tempFile, IDownloadNotification notification, DownloadOptions options)
            at System.Deployment.Application.DownloadManager.DownloadDeploymentManifestBypass(SubscriptionStore subStore, Uri& sourceUri, TempFile& tempFile, SubscriptionState& subState, IDownloadNotification notification, DownloadOptions options)
            at System.Deployment.Application.ApplicationActivator.PerformDeploymentActivation(Uri activationUri, Boolean isShortcut, String textualSubId, String deploymentProviderUrlFromExtension, BrowserSettings browserSettings, String& errorPageUrl)
            at System.Deployment.Application.ApplicationActivator.ActivateDeploymentWorker(Object state)
        --- Inner Exception ---
        System.Net.WebException
        - The remote name could not be resolved: 'radu-pc'
        - Source: System
        - Stack trace:
            at System.Net.HttpWebRequest.GetResponse()
            at System.Deployment.Application.SystemNetDownloader.DownloadSingleFile(DownloadQueueItem next)

COMPONENT STORE TRANSACTION DETAILS
    No transaction information is available.
```

**Comment by xfurry** [comment]
Ok...
Well this will be difficult for me to debug, because I don't have Win 8.
Anyway I will try to apply some updates and then you will be able to try again.

**Comment by suprsokr** [comment]
Hey, I ran into the same issue today. I didn't save the error, but it was the very similar to Ghosts.

The issue is that the program fails if the windows name of your computer has a dash. In the above issue (and in my own), we see Ghost has the windows pc name of 'radu-pc'

```
...
Deployment Provider url     : http://radu-pc/...
...
```

Renaming your pc to something without a dash will resolve the issue. I did so by pressing Windows key (to bring up search) , typing "name", clicking "View your pc name" and following the prompts from there. Be sure to re-extract the installation direction -- the program seems to cache your old pc name causing it to fail.
